name: example
publish_to: none
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  dart_pusher_channels:
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
