name: dart_pusher_channels
description: Dart implementation of client of Pusher Channels protocol, instrument to work with real-time applications. 
version: 1.2.1

environment:
  sdk: ^3.0.1

repository: https://github.com/kerimamansaryyev/dart_pusher_channels

platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:

dependencies:
  http: ^1.1.0
  meta: ^1.8.0
  pinenacl: ^0.5.1
  rxdart: ^0.27.7
  web_socket_channel: ^2.2.0

dev_dependencies:
  dart_code_metrics: 4.17.1
  lints: ^2.0.1
  test: ^1.22.1
