name: dart_pusher_channels
description: Dart implementation of client of Pusher Channels protocol, instrument to work with real-time applications. 
version: 0.2.3

environment:
  sdk: '>=2.16.1 <3.0.0'

repository: https://github.com/mcfugger/dart_pusher_channels

platforms:
  android:
  ios:
  web:
  windows:


dependencies:
  web_socket_channel: ^2.2.0
  http: ^0.13.2
  rxdart: ^0.27.3
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
